<script context="module" lang="ts">
  import type { Poem, RevealedWord } from "./types.svelte";

  export let Eagle: Poem = {
    title: "The Eagle",
    author: "Alfred, Lord Tennyson",
    rawPoem: [
      "He clasps the crag with crooked hands;",
      "Close to the sun in lonely lands,",
      "Ring'd with the azure world, he stands.",
      "\n",
      "The wrinkled sea beneath him crawls;",
      "He watches from his mountain walls,",
      "And like a thunderbolt he falls.",
    ],
  };

  export let RoadNotTaken: Poem = {
    title: "The road not taken",
    author: "Robert Frost",
    rawPoem: [
      "Two roads diverged in a yellow wood,",
      "And sorry I could not travel both",
      "And be one traveler, long I stood",
      "And looked down one as far as I could",
      "To where it bent in the undergrowth;",
      "\n",
      "Then took the other, as just as fair,",
      "And having perhaps the better claim,",
      "Because it was grassy and wanted wear;",
      "Though as for that the passing there",
      "Had worn them really about the same,",
      "\n",
      "And both that morning equally lay",
      "In leaves no step had trodden black.",
      "Oh, I kept the first for another day!",
      "Yet knowing how way leads on to way,",
      "I doubted if I should ever come back.",
      "\n",
      "I shall be telling this with a sigh",
      "Somewhere ages and ages hence:",
      "Two roads diverged in a wood, and I—",
      "I took the one less traveled by,",
      "And that has made all the difference.",
    ],
  };

  export let DulceEt: Poem = {
    title: "Dulce Et Decorum Est",
    author: "Wilfred Owen",
    rawPoem: [
      "Bent double, like old beggars under sacks,",
      "Knock-kneed, coughing like hags, we cursed through sludge,",
      " Till on the haunting flares we turned our backs",
      "And towards our distant rest began to trudge.",
      "Men marched asleep. Many had lost their boots",
      "But limped on, blood-shod. All went lame; all blind;",
      "Drunk with fatigue; deaf even to the hoots",
      "Of gas-shells dropping softly behind.",
      "\n",
      "Gas! GAS! Quick, boys!—An ecstasy of fumbling",
      "Fitting the clumsy helmets just in time,",
      "But someone still was yelling out and stumbling",
      "And flound’ring like a man in fire or lime.—",
      "Dim through the misty panes and thick green light,",
      "As under a green sea, I saw him drowning.",
      "\n",
      "In all my dreams before my helpless sight,",
      "He plunges at me, guttering, choking, drowning.",
      "\n",
      "If in some smothering dreams, you too could pace",
      "Behind the wagon that we flung him in,",
      "And watch the white eyes writhing in his face,",
      "His hanging face, like a devil’s sick of sin;",
      "If you could hear, at every jolt, the blood",
      "Come gargling from the froth-corrupted lungs,",
      "Obscene as cancer, bitter as the cud",
      "Of vile, incurable sores on innocent tongues,—",
      "My friend, you would not tell with such high zest",
      "To children ardent for some desperate glory,",
      "The old Lie: Dulce et decorum est",
      "Pro patria mori.",
    ],
  };
</script>
